import React, { useState, useEffect } from 'react';
import { Presentation, Slide } from '../../../services/presentationService';
import { ChevronLeft, ChevronRight, Download, X, Maximize2 } from 'lucide-react';

interface PresentationPreviewProps {
    presentation: Presentation;
    onDownload: () => void;
    onClose: () => void;
}

export default function PresentationPreview({ presentation, onDownload, onClose }: PresentationPreviewProps) {
    const [currentSlideIndex, setCurrentSlideIndex] = useState(0);
    const currentSlide = presentation.slides[currentSlideIndex];

    // Keyboard navigation
    useEffect(() => {
        const handleKeyDown = (e: KeyboardEvent) => {
            if (e.key === 'ArrowRight') nextSlide();
            if (e.key === 'ArrowLeft') prevSlide();
            if (e.key === 'Escape') onClose();
        };
        window.addEventListener('keydown', handleKeyDown);
        return () => window.removeEventListener('keydown', handleKeyDown);
    }, [currentSlideIndex]);

    const nextSlide = () => {
        if (currentSlideIndex < presentation.slides.length - 1) {
            setCurrentSlideIndex(prev => prev + 1);
        }
    };

    const prevSlide = () => {
        if (currentSlideIndex > 0) {
            setCurrentSlideIndex(prev => prev - 1);
        }
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-sm p-4 animate-in fade-in duration-200">
            <div className="bg-white dark:bg-gray-900 w-full max-w-7xl h-[90vh] rounded-2xl shadow-2xl flex flex-col overflow-hidden border border-gray-200 dark:border-gray-700">

                {/* Header */}
                <div className="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 z-10">
                    <div className="flex items-center gap-3 overflow-hidden">
                        <div className="bg-purple-100 dark:bg-purple-900/30 p-2 rounded-lg">
                            <Maximize2 className="w-5 h-5 text-purple-600 dark:text-purple-400" />
                        </div>
                        <div>
                            <h2 className="text-lg font-bold text-gray-900 dark:text-white truncate max-w-md">
                                {presentation.title}
                            </h2>
                            <p className="text-xs text-gray-500 dark:text-gray-400">
                                {presentation.slides.length} Slides • Generated by Lukas AI
                            </p>
                        </div>
                    </div>

                    <div className="flex items-center gap-3">
                        <button
                            onClick={onDownload}
                            className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white rounded-xl font-medium transition-all shadow-lg hover:shadow-purple-500/25"
                        >
                            <Download className="w-4 h-4" />
                            Download PPTX
                        </button>
                        <div className="h-8 w-px bg-gray-200 dark:bg-gray-700 mx-1" />
                        <button
                            onClick={onClose}
                            className="p-2 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg transition-colors text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
                        >
                            <X className="w-6 h-6" />
                        </button>
                    </div>
                </div>

                {/* Slide View Area */}
                <div className="flex-1 bg-gray-100 dark:bg-gray-950 p-8 flex items-center justify-center overflow-hidden relative select-none">

                    {/* Navigation Buttons */}
                    <button
                        onClick={prevSlide}
                        disabled={currentSlideIndex === 0}
                        className="absolute left-6 p-4 bg-white/90 dark:bg-gray-800/90 rounded-full shadow-xl hover:scale-110 hover:bg-white dark:hover:bg-gray-800 disabled:opacity-0 disabled:cursor-not-allowed transition-all z-10 text-gray-700 dark:text-gray-200"
                    >
                        <ChevronLeft className="w-6 h-6" />
                    </button>

                    <button
                        onClick={nextSlide}
                        disabled={currentSlideIndex === presentation.slides.length - 1}
                        className="absolute right-6 p-4 bg-white/90 dark:bg-gray-800/90 rounded-full shadow-xl hover:scale-110 hover:bg-white dark:hover:bg-gray-800 disabled:opacity-0 disabled:cursor-not-allowed transition-all z-10 text-gray-700 dark:text-gray-200"
                    >
                        <ChevronRight className="w-6 h-6" />
                    </button>

                    {/* The Slide */}
                    <div className="aspect-video w-full max-w-5xl bg-white shadow-2xl rounded-xl p-16 flex flex-col relative overflow-hidden transition-all duration-300 transform">

                        {/* Slide Number */}
                        <div className="absolute bottom-6 right-8 text-gray-300 text-sm font-mono">
                            {currentSlideIndex + 1} / {presentation.slides.length}
                        </div>

                        {/* Title Slide Layout */}
                        {currentSlide.type === 'title' && (
                            <div className="flex-1 flex flex-col justify-center items-center text-center animate-in zoom-in-95 duration-300">
                                <h1 className="text-6xl font-extrabold text-gray-900 mb-8 leading-tight tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-gray-900 to-gray-700">
                                    {currentSlide.title}
                                </h1>
                                <div className="space-y-3">
                                    {currentSlide.content?.map((line, i) => (
                                        <p key={i} className="text-2xl text-gray-500 font-light">
                                            {line}
                                        </p>
                                    ))}
                                </div>
                                <div className="mt-12 w-24 h-1 bg-gradient-to-r from-purple-500 to-blue-500 rounded-full" />
                            </div>
                        )}

                        {/* Content/Conclusion Slide Layout */}
                        {(currentSlide.type === 'content' || currentSlide.type === 'conclusion') && (
                            <div className="flex-1 flex flex-col animate-in zoom-in-95 duration-300">
                                <h2 className="text-4xl font-bold text-gray-900 mb-10 border-b-2 border-gray-100 pb-6 flex items-center gap-4">
                                    <span className="w-3 h-12 bg-blue-600 rounded-full block" />
                                    {currentSlide.title}
                                </h2>

                                <div className="flex gap-12 flex-1 items-start">
                                    <div className="flex-1 space-y-6">
                                        {currentSlide.content?.map((point, i) => (
                                            <div key={i} className="flex items-start gap-4 group">
                                                <div className="w-2 h-2 rounded-full bg-blue-500 mt-3.5 shrink-0 group-hover:scale-125 transition-transform" />
                                                <p className="text-2xl text-gray-700 leading-relaxed font-light">
                                                    {point}
                                                </p>
                                            </div>
                                        ))}
                                    </div>

                                    {currentSlide.imageUrl && (
                                        <div className="w-1/3 shrink-0">
                                            <div className="relative group">
                                                <div className="absolute -inset-1 bg-gradient-to-r from-purple-600 to-blue-600 rounded-lg blur opacity-25 group-hover:opacity-50 transition duration-200"></div>
                                                <img
                                                    src={currentSlide.imageUrl}
                                                    alt="Slide visual"
                                                    className="relative w-full h-auto rounded-lg shadow-lg object-cover bg-gray-100"
                                                />
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </div>
                        )}
                    </div>
                </div>

                {/* Thumbnails Footer */}
                <div className="h-32 bg-white dark:bg-gray-900 border-t border-gray-200 dark:border-gray-700 p-4 flex gap-4 overflow-x-auto items-center">
                    {presentation.slides.map((slide, idx) => (
                        <button
                            key={idx}
                            onClick={() => setCurrentSlideIndex(idx)}
                            className={`group relative aspect-video h-20 rounded-lg border-2 transition-all shrink-0 flex flex-col items-center justify-center bg-gray-50 dark:bg-gray-800 overflow-hidden ${currentSlideIndex === idx
                                    ? 'border-blue-500 ring-2 ring-blue-200 dark:ring-blue-900 scale-105'
                                    : 'border-transparent hover:border-gray-300 dark:hover:border-gray-600 opacity-70 hover:opacity-100'
                                }`}
                        >
                            <span className="text-xs font-bold text-gray-400 group-hover:text-gray-600 dark:group-hover:text-gray-300">
                                {idx + 1}
                            </span>
                            <div className="absolute bottom-0 left-0 right-0 h-1 bg-gray-200 dark:bg-gray-700">
                                {currentSlideIndex === idx && (
                                    <div className="h-full bg-blue-500 w-full" />
                                )}
                            </div>
                        </button>
                    ))}
                </div>
            </div>
        </div>
    );
}
